# Semana03.property = semana03 profile Prod
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-prod:3306/estudiantesDEBER-prod
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect